name: amredi
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0
  flutter_riverpod: ^2.4.9
  hive_flutter: ^1.1.0
  image_picker: ^1.0.7
  http: ^1.2.0
  location: ^5.0.0
  permission_handler: ^11.3.0
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
        - asset: fonts/Roboto/Roboto-Bold.ttf
        - asset: fonts/Roboto/Roboto-Thin.ttf
          # style: italic
    # - family: Poppins
    #   fonts:
    #     - asset: fonts/Poppins/Poppins-BolTrajanPro.ttf
    #     - asset: fonts/Poppins/Poppins-BolTrajanPro_Bold.ttf
    #       weight: 700

